### ISSUE TITLE
使用docker部署时出现错误：Browser APIs are not available on the server

### ISSUE THREAD

**Issue by legical** [gcloudlab/QA#7]
[dockerfile](https://github.com/gcloudlab/QA/blob/main/dockerfile)

Error:
![](https://raw.githubusercontent.com/leegical/Blog_img/master/md_img202303241511537.png)

**Comment by yesmore** [comment]
抱歉，这是我的疏忽，我并没有测试过这个Dockerfile能否部署，因为这是参考 [这个](https://github.com/ddiu8081/chatgpt-demo/blob/main/Dockerfile) 项目的，你可以根据他的来部署
