### ISSUE TITLE
netlify部署后访问链接报错

### ISSUE THREAD

**Issue by Taoshuaifei** [gcloudlab/QA#9]
老哥，我用netlify按教程部署后访问链接报错，没用过netlify，不知道哪的问题，您有空的话看下

`This edge function has crashed
An unhandled error in the function code triggered the following message:

The deployment failed while serving the request.
Connection details
Netlify internal ID: 01H074EFQQEH9Z40VKJYXFH8Q6`

**Comment by yesmore** [comment]
不推荐用netlify部署
